#!/usr/bin/ruby
################################################################################
# buildbob
#
# Runs bob on all .bob files in the current directory. Strips the .bob from the
# end of the filename and saves the output in that file.
# -----------------------------------------------------------------------------
# (C) Copyright 2009 William Madden
# 
# This file is part of Bob.
# 
# Bob is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Bob is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# Foobar.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

path_to_bob = '/home/will/Projects/Personal/Bob/src/bob.rb'

Dir.glob("*.bob") do |file|
  if /(.*)\.bob/ === file
    filename = $1
    puts "Building #{file} > #{filename}"
    `#{path_to_bob} #{file} > #{filename}`
  end
end
